version: '3.8'

services:
  dnsmasq:
    image: andyshinn/dnsmasq
    container_name: dnsmasq
    ports:
      - "53:53/udp"
    volumes:
      - ./dnsmasq/dnsmasq.conf:/etc/dnsmasq.conf
    restart: unless-stopped
