version: '3.8'

services:
  nextcloud:
    image: nextcloud
    container_name: nextcloud
    volumes:
      - ./nextcloud:/var/www/html
    environment:
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      NEXTCLOUD_ADMIN_USER: ${NEXTCLOUD_ADMIN_USER}
      NEXTCLOUD_ADMIN_PASSWORD: ${NEXTCLOUD_ADMIN_PASSWORD}
    networks:
      - nextcloud_network
      
  nginx:
    image: nginx:alpine
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nextcloud:/var/www/html
      - ./certs:/etc/nginx/certs
    ports:
      - "80:80"
      - "443:443"
    environment:
      - DOMAIN=${DOMAIN}
    depends_on:
      - nextcloud
    networks:
      - nextcloud_network

volumes:
  nextcloud_data:
  db_data:

networks:
  nextcloud_network:
